### PR TITLE
Figma based view for list spacings

### PR DESCRIPTION
**Pull request by DanielJackson-Oslo**
Mostly centered around a partial for rendering a space listing in the search results.

Loads of TODOs left in _space_listing.html.erb for when main is ready for it, but I think this can be merged for now:
 
- Remove hard coded values, and replace with dynamic ones from Rails.
  - Image. (TBD: How do we choose which image to show?)
  - Title (Frederik II -> space.title)
  - School_Level (VGS -> space.school_level)!? We might want to eliminate this one
  - Rating (4.2 -> space.rating)
  - Number of Ratings (5 -> space.number_of_ratings)
  - Type (Skole -> space.type)!? We might want to eliminate this one
  - Number of people it fits (1200 elever -> space.fits_people)!? We might want to change this one to say something other than elever
  - Facility listing based on search (currently, overnatting, kjøkken, lydanlegg, dansegulv)
    - Probability for each facility, as shown below
    - Icon for each? Not currently shown, but in Figma

### CODE REVIEW

**Comment by DanielJackson-Oslo** [comment]
Re-opened with new SVG names :) And added a simple icon for the "impossible" state.

**Comment by DanielJackson-Oslo** [comment]
Test comment, to see if the webhook to Discord works

**Comment by DanielJackson-Oslo** [comment]
Test comment

**Review by asolvang — APPROVED** [review]
:+1:

**Review by mathias234 — APPROVED** [review]

**Comment by asolvang** [comment]
[Figma based view fro listing spacings](https://trello.com/c/pYanrcyD/23-figma-based-view-fro-listing-spacings)

**Pull request merged**
