### PR TITLE
Extend space model

### PR DESCRIPTION
**Pull request by DanielJackson-Oslo**
Extends space model with several new additions, to more closely align with what the Figma sketches show: 

- Added ActionText
- Added several rich text fields to Space
- Changed lat/long to lat/lng (as that seems to be the standard way to shorten them), and changed type to decimal  with 6 decimals in accordance with Google Maps recommendations for lat/lng to make it easier to filter by them.
- Added a title field and organization_number field to Space. Title field is obligatory.

Not changed any edit fields or create fields. 

With these changes, I think the model is ready for importing 3000 schools from NSR, as we have done on dev.lokaler.lnu.no. 

Missing, but unsure if they should be added or not before we push:
 
- [ ] Tests
- [ ] Validation for Space
- [x] Changing edit form for Space
- [x] Changing new form for Space

### CODE REVIEW

**Comment by DanielJackson-Oslo** [comment]
Missing, but unsure if they should be added or not before we push:
 
- [ ] Tests
- [ ] Validation 
- [ ] Changing edit and new forms for Space

**Comment by DanielJackson-Oslo** [comment]
[Add all required Space fields, and actionText](https://trello.com/c/v38E3MtP/36-add-all-required-space-fields-and-actiontext)

**Review by mathias234 — APPROVED** [review]
I added title to the form to be able to test the other changes. I think it's best if we try to keep these CRUD forms working with all our changes as it's the only way outside of the rails console to add new things.

Otherwise it looks good to me

**Comment by DanielJackson-Oslo** [comment]
> I added title to the form to be able to test the other changes. I think it's best if we try to keep these CRUD forms working with all our changes as it's the only way outside of the rails console to add new things.
> 
> Otherwise it looks good to me

I can add CRUD forms for all of the new fields before we merge. Will do it this morning :)

**Comment by DanielJackson-Oslo** [comment]
Now we have full CRUD support, and also created a primitive space/show.erb.html.

**Review by mathias234 — APPROVED** [review]
Looks good to me!

**Pull request merged**
