### PR TITLE
Adding release db:migrate to Procfile

### PR DESCRIPTION
**Pull request by Laaknor**
This is how I do DB:Migrate in another project I've got

### CODE REVIEW

**Comment by mathias234** [comment]
Seems to kill foreman after the release part is done
image
If we want to use procfile for this we probably need to use a seperate procfile for dev e.g `foreman s -f Procfile.dev` we have that file but I don't believe anyone uses it

**Comment by Laaknor** [comment]
That is not related to the changes I've done (release is supposed to exit after it's run). Foreman has not worked for me for a long time. But according to heroku documentation, this is the way to add db:migrate before new production code is put in production https://devcenter.heroku.com/articles/release-phase

**Comment by mathias234** [comment]
> ....
Because `release` exits, it seems that foreman ends up sending SIGTERM/SIGKILL to the other long-running processes, which ends up killing webpack and guard, which should be running during development. 
Not sure why foreman isn't working for you, but it is working in main without this change.

**Comment by Laaknor** [comment]
Removed release from my Procfile, and now suddently it works (didn't on saturday when I tested it). Closeing this, as we must find another way of doing it.

**Comment by DanielJackson-Oslo** [comment]
Could we have a seperate procfile for heroku/prod?

**Pull request closed without merging**
