### PR TITLE
Styling captions

### PR DESCRIPTION
**Pull request by DanielJackson-Oslo**
## Adds full screen mode for images

image

## Styles captions on both thumbnail and full screen

image

If the text is too long it clips on the thumbnail:

image

But shows on the fullscreen version:
image

## Adds seeds for the different caption challenges

# missing

- [ ] Tests for full screen image controller
- [ ] Turbo frame it? Would make it nicer, but not sure we need to.
- [ ] Lots of common boiler plate between the two slider pages, might want to abstract that away

### CODE REVIEW

**Comment by DanielJackson-Oslo** [comment]
@mathias234 Which of these do you think it's worth it doing, over going to the next trello card? 


- [ ] Tests for full screen image controller
- [ ] Turbo frame it? Would make it nicer, but not sure we need to.
- [ ]  Lots of common boiler plate between the two slider pages, might want to abstract that away

**Review by mathias234 — CHANGES_REQUESTED** [review]
Looks like  the images is too large on my computer when in fullscreen resulting in having to scroll to see the captions & credits

**Comment by DanielJackson-Oslo** [comment]
> Looks like the images is too large on my computer when in fullscreen resulting in having to scroll to see the captions & credits

Should be fixed now! Took forever to fight with Splide to get it done, and looks a bit corny on very tall screens, but works!

Now the text and image should always fit on the screen:

image
image

**Review by mathias234 — APPROVED** [review]
Seems to work better now 👍 

As for the missing features you mentioned
 * _Tests for full screen image controller_
 This can be done in a seperate PR now that capybara tests are enabled 
 * _Turbo frame it? Would make it nicer, but not sure we need to._
 I think this is probably not needed
 * _Lots of common boiler plate between the two slider pages, might want to abstract that away_
 I looked at both of the versions and they seem so different enough that trying to abstract it will probably not really work, they don't seem to share much in terms of tailwind classes and their layouts are quite a bit different. If you think there's something that can easily be abstracted then do it here

**Pull request merged**
